"""
PDF Generator — produces beautiful professional invoices/receipts.
Supports: A4, A5, Letter (US 8.5x11), Legal (8.5x14)
"""

import os
import tempfile
from datetime import datetime
from reportlab.lib.pagesizes import A4, A5, LETTER, LEGAL
from reportlab.lib import colors
from reportlab.lib.units import mm
from reportlab.lib.styles import ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
)
from reportlab.pdfgen import canvas
from reportlab.lib.enums import TA_LEFT, TA_RIGHT, TA_CENTER

# ── Page size map ─────────────────────────────────────────────────────────────
PAGE_SIZES = {
    "A4":     A4,
    "A5":     A5,
    "Letter": LETTER,
    "Legal":  LEGAL,
}
PAGE_SIZE_LABELS = {
    "A4":     "A4 (210×297 mm)",
    "A5":     "A5 (148×210 mm)",
    "Letter": "US Letter (8.5×11 in)",
    "Legal":  "US Legal (8.5×14 in)",
}

# ── Brand colours ─────────────────────────────────────────────────────────────
DARK_NAVY   = colors.HexColor("#0D1B2A")
ACCENT_BLUE = colors.HexColor("#1565C0")
ACCENT_TEAL = colors.HexColor("#00897B")
LIGHT_BG    = colors.HexColor("#F5F7FA")
STRIPE_BG   = colors.HexColor("#EEF2F7")
MID_GREY    = colors.HexColor("#78909C")
TEXT_DARK   = colors.HexColor("#1A1A2E")
WHITE       = colors.white
SUCCESS     = colors.HexColor("#2E7D32")
DIVIDER     = colors.HexColor("#CFD8DC")

CURRENCIES = {
    "USD": "$", "EUR": "€", "GBP": "£", "TRY": "₺",
    "AED": "AED ", "SAR": "SAR ", "IQD": "IQD "
}


class InvoiceCanvas(canvas.Canvas):
    def __init__(self, *args, inv_type="Invoice", page_w=None, page_h=None, **kwargs):
        super().__init__(*args, **kwargs)
        self._inv_type = inv_type
        self._page_w = page_w or A4[0]
        self._page_h = page_h or A4[1]
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self._draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def _draw_page_decorations(self, total_pages):
        W, H = self._page_w, self._page_h
        bar_h = 8 * mm
        # Top accent bar
        self.setFillColor(ACCENT_BLUE)
        self.rect(0, H - bar_h, W, bar_h, fill=1, stroke=0)
        # Thin teal accent
        self.setFillColor(ACCENT_TEAL)
        self.rect(0, H - bar_h - 2 * mm, W, 2 * mm, fill=1, stroke=0)
        # Decorative corner shape
        self.saveState()
        self.setFillColor(colors.HexColor("#E8EEF7"))
        path = self.beginPath()
        path.moveTo(W * 0.72, H)
        path.lineTo(W, H)
        path.lineTo(W, H * 0.72)
        path.close()
        self.drawPath(path, fill=1, stroke=0)
        self.restoreState()
        # Footer line
        self.setStrokeColor(DIVIDER)
        self.setLineWidth(0.5)
        self.line(20 * mm, 14 * mm, W - 20 * mm, 14 * mm)
        # Footer text
        self.setFillColor(MID_GREY)
        self.setFont("Helvetica", 7.5)
        self.drawString(20 * mm, 10 * mm,
                        f"Generated by Invoice Bot  •  {datetime.now().strftime('%d %b %Y %H:%M')}")
        self.drawRightString(W - 20 * mm, 10 * mm,
                             f"Page {self._pageNumber} of {total_pages}")


def _sym(inv):
    return CURRENCIES.get(inv.get("currency", "USD"), "$")

def _fmt(amount, inv):
    return f"{_sym(inv)}{amount:,.2f}"

def _calc(inv):
    items    = inv.get("items", [])
    subtotal = sum(i["qty"] * i["price"] for i in items)
    disc_pct = inv.get("discount", 0)
    tax_pct  = inv.get("tax_rate", 0)
    disc_amt = subtotal * disc_pct / 100
    taxable  = subtotal - disc_amt
    tax_amt  = taxable * tax_pct / 100
    total    = taxable + tax_amt
    return subtotal, disc_pct, disc_amt, tax_pct, tax_amt, total

def _styles(scale=1.0):
    """Return style dict, scaled for smaller page sizes like A5."""
    def s(base): return max(6, int(base * scale))
    return {
        "doc_type":          ParagraphStyle("doc_type",          fontName="Helvetica-Bold",       fontSize=s(28), textColor=WHITE,     alignment=TA_RIGHT),
        "doc_number":        ParagraphStyle("doc_number",        fontName="Helvetica",            fontSize=s(11), textColor=colors.HexColor("#B0BEC5"), alignment=TA_RIGHT),
        "company_name":      ParagraphStyle("company_name",      fontName="Helvetica-Bold",       fontSize=s(14), textColor=DARK_NAVY, spaceAfter=2),
        "company_info":      ParagraphStyle("company_info",      fontName="Helvetica",            fontSize=s(8),  textColor=MID_GREY,  leading=s(13)),
        "section_label":     ParagraphStyle("section_label",     fontName="Helvetica-Bold",       fontSize=s(7),  textColor=MID_GREY,  spaceAfter=2, letterSpacing=1.0),
        "client_name":       ParagraphStyle("client_name",       fontName="Helvetica-Bold",       fontSize=s(12), textColor=TEXT_DARK, spaceAfter=3),
        "client_info":       ParagraphStyle("client_info",       fontName="Helvetica",            fontSize=s(8),  textColor=MID_GREY,  leading=s(13)),
        "meta_label":        ParagraphStyle("meta_label",        fontName="Helvetica-Bold",       fontSize=s(7),  textColor=MID_GREY),
        "meta_value":        ParagraphStyle("meta_value",        fontName="Helvetica",            fontSize=s(8),  textColor=TEXT_DARK),
        "table_header":      ParagraphStyle("table_header",      fontName="Helvetica-Bold",       fontSize=s(8),  textColor=WHITE),
        "table_cell":        ParagraphStyle("table_cell",        fontName="Helvetica",            fontSize=s(8),  textColor=TEXT_DARK, leading=s(12)),
        "table_cell_right":  ParagraphStyle("table_cell_right",  fontName="Helvetica",            fontSize=s(8),  textColor=TEXT_DARK, alignment=TA_RIGHT),
        "total_label":       ParagraphStyle("total_label",       fontName="Helvetica-Bold",       fontSize=s(9),  textColor=TEXT_DARK, alignment=TA_RIGHT),
        "total_value":       ParagraphStyle("total_value",       fontName="Helvetica",            fontSize=s(9),  textColor=TEXT_DARK, alignment=TA_RIGHT),
        "grand_total_label": ParagraphStyle("grand_total_label", fontName="Helvetica-Bold",       fontSize=s(12), textColor=WHITE,     alignment=TA_RIGHT),
        "grand_total_value": ParagraphStyle("grand_total_value", fontName="Helvetica-Bold",       fontSize=s(13), textColor=WHITE,     alignment=TA_RIGHT),
        "notes_label":       ParagraphStyle("notes_label",       fontName="Helvetica-Bold",       fontSize=s(8),  textColor=ACCENT_BLUE, spaceAfter=3),
        "notes_text":        ParagraphStyle("notes_text",        fontName="Helvetica",            fontSize=s(8),  textColor=MID_GREY,  leading=s(13)),
        "paid_stamp":        ParagraphStyle("paid_stamp",        fontName="Helvetica-Bold",       fontSize=s(32), textColor=colors.HexColor("#C8E6C9"), alignment=TA_CENTER),
        "thank_you":         ParagraphStyle("thank_you",         fontName="Helvetica-BoldOblique",fontSize=s(9),  textColor=ACCENT_TEAL, alignment=TA_CENTER),
    }


def generate_invoice_pdf(inv: dict) -> str:
    page_key  = inv.get("page_size", "A4")
    page_size = PAGE_SIZES.get(page_key, A4)
    W, H      = page_size
    inv_type  = inv.get("type", "Invoice")
    company   = inv.get("company", {})
    sym       = _sym(inv)

    # Scale fonts for A5 (smaller canvas)
    scale = 0.78 if page_key == "A5" else 1.0
    S     = _styles(scale)

    # Margins
    mg = 18 * mm if page_key == "A5" else 20 * mm
    tm = 26 * mm if page_key == "A5" else 28 * mm

    tmp  = tempfile.NamedTemporaryFile(suffix=".pdf", delete=False)
    path = tmp.name
    tmp.close()

    doc = SimpleDocTemplate(
        path, pagesize=page_size,
        leftMargin=mg, rightMargin=mg,
        topMargin=tm, bottomMargin=20 * mm,
    )
    dw    = doc.width
    story = []

    def ph(text, style_key):
        return Paragraph(text, S[style_key])

    # ── 1. HEADER ─────────────────────────────────────────────────────────────
    company_block = [ph(company.get("name", "Your Company"), "company_name")]
    for field in ("address", "email", "phone"):
        val = company.get(field, "")
        if val:
            company_block.append(ph(val.replace("\n", "<br/>"), "company_info"))
    if company.get("website"):
        company_block.append(ph(company["website"], "company_info"))
    if company.get("tax_id"):
        company_block.append(ph(f"Tax ID: {company['tax_id']}", "company_info"))

    doc_block = [
        ph(inv_type.upper(), "doc_type"),
        ph(f"#{inv.get('number','0001')}", "doc_number"),
    ]

    hdr = Table([[company_block, doc_block]], colWidths=[dw * 0.55, dw * 0.45])
    hdr.setStyle(TableStyle([
        ("BACKGROUND",    (1, 0), (1, 0), ACCENT_BLUE),
        ("VALIGN",        (0, 0), (-1, -1), "TOP"),
        ("ALIGN",         (1, 0), (1, 0), "RIGHT"),
        ("TOPPADDING",    (1, 0), (1, 0), 10),
        ("BOTTOMPADDING", (1, 0), (1, 0), 10),
        ("RIGHTPADDING",  (1, 0), (1, 0), 12),
        ("LEFTPADDING",   (1, 0), (1, 0), 8),
    ]))
    story += [hdr, Spacer(1, 5 * mm)]

    # ── 2. BILL TO + META ─────────────────────────────────────────────────────
    client_block = [ph("BILL TO", "section_label"), ph(inv.get("client_name", "—"), "client_name")]
    for field in ("client_address", "client_email", "client_phone"):
        val = inv.get(field, "")
        if val:
            client_block.append(ph(val.replace("\n", "<br/>"), "client_info"))

    meta_rows = [
        [ph("DATE ISSUED", "meta_label"), ph(inv.get("date", "—"),     "meta_value")],
        [ph("DUE DATE",    "meta_label"), ph(inv.get("due_date", "—"), "meta_value")],
        [ph("CURRENCY",    "meta_label"), ph(inv.get("currency","USD"),"meta_value")],
        [ph("PAGE SIZE",   "meta_label"), ph(page_key,                  "meta_value")],
    ]
    if company.get("tax_id"):
        meta_rows.append([ph("TAX ID", "meta_label"), ph(company["tax_id"], "meta_value")])

    meta_tbl = Table(meta_rows, colWidths=[26 * mm * scale, 36 * mm * scale])
    meta_tbl.setStyle(TableStyle([
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [LIGHT_BG, STRIPE_BG]),
        ("TOPPADDING",     (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING",  (0, 0), (-1, -1), 3),
        ("LEFTPADDING",    (0, 0), (-1, -1), 5),
        ("RIGHTPADDING",   (0, 0), (-1, -1), 5),
    ]))

    info = Table([[client_block, "", meta_tbl]], colWidths=[dw * 0.44, dw * 0.04, dw * 0.52])
    info.setStyle(TableStyle([("VALIGN", (0,0),(-1,-1),"TOP"), ("ALIGN",(2,0),(2,0),"RIGHT")]))
    story += [info, Spacer(1, 6 * mm)]

    # ── 3. LINE ITEMS TABLE ───────────────────────────────────────────────────
    cn = dw * 0.04
    cd = dw * 0.37
    cu = dw * 0.09
    cq = dw * 0.10
    cp = dw * 0.18
    ct = dw * 0.20

    headers = [ph("#","table_header"), ph("DESCRIPTION","table_header"),
               ph("UNIT","table_header"), ph("QTY","table_header"),
               ph("UNIT PRICE","table_header"), ph("AMOUNT","table_header")]
    rows = [headers]
    for idx, item in enumerate(inv.get("items", []), 1):
        lt = item["qty"] * item["price"]
        rows.append([
            ph(str(idx),                      "table_cell"),
            ph(item.get("name",""),           "table_cell"),
            ph(item.get("unit","pc"),         "table_cell"),
            ph(f'{item["qty"]:g}',            "table_cell_right"),
            ph(f'{sym}{item["price"]:,.2f}',  "table_cell_right"),
            ph(f'{sym}{lt:,.2f}',             "table_cell_right"),
        ])

    stripe = [("BACKGROUND",(0,i),(-1,i), LIGHT_BG if i%2==0 else WHITE)
              for i in range(1, len(rows))]
    pad    = 6 if page_key != "A5" else 4

    items_tbl = Table(rows, colWidths=[cn,cd,cu,cq,cp,ct], repeatRows=1)
    items_tbl.setStyle(TableStyle([
        ("BACKGROUND",    (0,0),(-1,0),  DARK_NAVY),
        ("FONTNAME",      (0,0),(-1,0),  "Helvetica-Bold"),
        ("FONTSIZE",      (0,0),(-1,0),  8 * scale),
        ("TOPPADDING",    (0,0),(-1,0),  pad+2),
        ("BOTTOMPADDING", (0,0),(-1,0),  pad+2),
        ("ALIGN",         (3,0),(-1,0),  "RIGHT"),
        ("ALIGN",         (3,1),(-1,-1), "RIGHT"),
        ("FONTNAME",      (0,1),(-1,-1), "Helvetica"),
        ("FONTSIZE",      (0,1),(-1,-1), 8 * scale),
        ("TOPPADDING",    (0,1),(-1,-1), pad),
        ("BOTTOMPADDING", (0,1),(-1,-1), pad),
        ("LEFTPADDING",   (0,0),(-1,-1), 6),
        ("RIGHTPADDING",  (0,0),(-1,-1), 6),
        ("LINEBELOW",     (0,0),(-1,0),  0.5, ACCENT_TEAL),
        ("LINEBELOW",     (0,1),(-1,-1), 0.3, DIVIDER),
        ("VALIGN",        (0,0),(-1,-1), "MIDDLE"),
        *stripe,
    ]))
    story += [items_tbl, Spacer(1, 4 * mm)]

    # ── 4. TOTALS ─────────────────────────────────────────────────────────────
    subtotal, disc_pct, disc_amt, tax_pct, tax_amt, total = _calc(inv)

    tot_rows = [[ph("Subtotal","total_label"), ph(_fmt(subtotal,inv),"total_value")]]
    if disc_pct:
        tot_rows.append([ph(f"Discount ({disc_pct:g}%)","total_label"),
                         ph(f"- {_fmt(disc_amt,inv)}","total_value")])
    if tax_pct:
        tot_rows.append([ph(f"Tax ({tax_pct:g}%)","total_label"),
                         ph(f"+ {_fmt(tax_amt,inv)}","total_value")])

    tot_tbl = Table(tot_rows, colWidths=[dw * 0.65, dw * 0.35])
    tot_tbl.setStyle(TableStyle([
        ("ALIGN",         (0,0),(-1,-1), "RIGHT"),
        ("TOPPADDING",    (0,0),(-1,-1), 3),
        ("BOTTOMPADDING", (0,0),(-1,-1), 3),
        ("LINEBELOW",     (0,-1),(-1,-1), 0.5, DIVIDER),
    ]))
    story += [tot_tbl, Spacer(1, 2 * mm)]

    grand = Table([[ph(f"TOTAL {inv.get('currency','USD')}","grand_total_label"),
                    ph(_fmt(total,inv),"grand_total_value")]],
                  colWidths=[dw*0.65, dw*0.35])
    grand.setStyle(TableStyle([
        ("BACKGROUND",    (0,0),(-1,0), ACCENT_BLUE),
        ("ALIGN",         (0,0),(-1,-1),"RIGHT"),
        ("TOPPADDING",    (0,0),(-1,-1), 9),
        ("BOTTOMPADDING", (0,0),(-1,-1), 9),
        ("LEFTPADDING",   (0,0),(-1,-1),12),
        ("RIGHTPADDING",  (0,0),(-1,-1),12),
    ]))
    story += [grand, Spacer(1, 5 * mm)]

    # PAID stamp for receipts
    if inv_type == "Receipt":
        paid = Table([[ph("CHECK MARK PAID","paid_stamp")]], colWidths=[dw])
        paid.setStyle(TableStyle([
            ("BACKGROUND",    (0,0),(0,0), SUCCESS),
            ("TOPPADDING",    (0,0),(0,0), 5),
            ("BOTTOMPADDING", (0,0),(0,0), 5),
        ]))
        story += [paid, Spacer(1, 4*mm)]

    # ── 5. NOTES ──────────────────────────────────────────────────────────────
    notes = inv.get("notes","")
    if notes:
        story.append(HRFlowable(width="100%", thickness=0.5, color=DIVIDER))
        story.append(Spacer(1, 3*mm))
        story.append(ph("NOTES & PAYMENT TERMS","notes_label"))
        story.append(ph(notes.replace("\n","<br/>"),"notes_text"))
        story.append(Spacer(1, 4*mm))

    # ── 6. THANK YOU ──────────────────────────────────────────────────────────
    story.append(HRFlowable(width="100%", thickness=0.5, color=DIVIDER))
    story.append(Spacer(1, 4*mm))
    thank = "Thank you for your business!" if inv_type == "Invoice" else "Thank you for your payment!"
    story.append(ph(thank, "thank_you"))

    # ── BUILD ─────────────────────────────────────────────────────────────────
    def make_canvas(filename, **kwargs):
        return InvoiceCanvas(filename, inv_type=inv_type, page_w=W, page_h=H, **kwargs)

    doc.build(story, canvasmaker=make_canvas)
    return path
